# @local=localhost
# @port=3456
# @username=max
@username=maxcian

### GET /
GET http://127.0.0.1:3456/agfsadga HTTP/1.1

### POST /login
POST http://127.0.0.1:3456/login HTTP/1.1


### register
POST http://127.0.0.1:3456/register HTTP/1.1
Content-Type: application/json

{
    "username": "maxcian"
}

### balance
GET http://127.0.0.1:3456/balance/maxcian HTTP/1.1

### deposit
POST http://127.0.0.1:3456/deposit/maxcian HTTP/1.1
Content-Type: application/json

{
    "amount": 999
}

# =================================================================
# Echo server API referneces
# =================================================================

### GET echo API
GET http://localhost:12345/get?aaa=bbb HTTP/1.1
X-test-headers: hahapoint

### POST echo API (text/plain)
POST http://localhost:12345/post?foo=bar HTTP/1.1
Content-Type: text/plain
X-test-foobar: hello world

haha, this is body text


### POST echo API (text/json)
POST http://localhost:12345/post?foo=bar HTTP/1.1
Content-Type: application/json
X-test-foobar: hello world

{"foo": "bar", "nested": [123, 456, 789]}

